# Generated by Django 5.2.7 on 2025-11-08 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Torneo', '0005_alter_equipo_capitan'),
        ('fase_de_grupos', '0004_alter_equipogrupo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('grupos', 'Fase de Grupos'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinal'), ('tercer_puesto', 'Tercer Puesto'), ('final', 'Final')], default='grupos', max_length=20)),
                ('jornada', models.PositiveIntegerField(help_text='Número de jornada en la fase')),
                ('fecha_hora', models.DateTimeField()),
                ('cancha', models.CharField(blank=True, help_text='Nombre de la cancha', max_length=100)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_juego', 'En Juego'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('goles_local', models.PositiveIntegerField(default=0)),
                ('goles_visitante', models.PositiveIntegerField(default=0)),
                ('persona_finalizo_partido', models.CharField(blank=True, help_text='Usuario que registró el resultado', max_length=50, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='Torneo.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='Torneo.equipo')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fase_de_grupos.grupo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='Torneo.torneo')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['fecha_hora', 'torneo'],
                'unique_together': {('grupo', 'equipo_local', 'equipo_visitante', 'jornada'), ('torneo', 'equipo_local', 'equipo_visitante', 'fase')},
            },
        ),
    ]
