# Generated by Django 5.2.7 on 2026-02-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='goles_penaltis_local',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_penaltis_visitante',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
