# Generated by Django 5.2.7 on 2026-02-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_partido_goles_penaltis_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='cancha',
            field=models.CharField(blank=True, help_text='Nombre de la cancha', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
