# Generated by Django 5.2.7 on 2026-02-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0003_alter_partido_cancha_alter_partido_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_juego', 'En Juego'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('cancelado', 'Cancelado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20),
        ),
    ]
