# Generated by Django 5.2.7 on 2025-11-08 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Torneo', '0005_alter_equipo_capitan'),
        ('partidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goleador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField(help_text='Minuto de gol')),
                ('tipo_gol', models.CharField(choices=[('normal', 'Gol Normal'), ('penalti', 'Penalti'), ('autogol', 'Autogol')], default='normal', max_length=10)),
                ('es_autogol', models.BooleanField(default=False)),
                ('es_penalti', models.BooleanField(default=False)),
                ('fallo_penalti', models.BooleanField(default=False, help_text='Si falló un penalti')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneo.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to=settings.AUTH_USER_MODEL)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goles', to='partidos.partido')),
            ],
            options={
                'verbose_name': 'Gol',
                'verbose_name_plural': 'Goles',
                'ordering': ['partido', 'minuto'],
            },
        ),
    ]
