# Generated by Django 5.2.7 on 2026-02-20 13:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partidos', '0004_alter_partido_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciaPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gol', 'Gol'), ('amarilla', 'Tarjeta Amarilla'), ('azul', 'Tarjeta Azul'), ('roja', 'Tarjeta Roja'), ('falta', 'Falta Técnica')], max_length=50)),
                ('minuto', models.PositiveSmallIntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('periodo', models.PositiveSmallIntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='partidos.partido')),
            ],
            options={
                'ordering': ['periodo', 'minuto'],
            },
        ),
    ]
