# Generated by Django 5.2.7 on 2025-11-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Torneo', '0004_alter_torneo_max_equipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='A,B,C etc...', max_length=1)),
                ('equipos', models.ManyToManyField(to='Torneo.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneo.torneo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'unique_together': {('torneo', 'nombre')},
            },
        ),
    ]
