# Generated by Django 5.2.7 on 2025-11-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneo', '0005_alter_equipo_capitan'),
        ('fase_de_grupos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('partidos_jugados', models.IntegerField(default=0)),
                ('partidos_ganados', models.IntegerField(default=0)),
                ('partidos_empatados', models.IntegerField(default=0)),
                ('partidos_perdidos', models.IntegerField(default=0)),
                ('goles_favor', models.IntegerField(default=0)),
                ('goles_contra', models.IntegerField(default=0)),
                ('tarjeta_amarilla', models.IntegerField(default=0)),
                ('tarjeta_roja', models.IntegerField(default=0)),
                ('tarjeta_azul', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Torneo.equipo')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fase_de_grupos.grupo')),
            ],
            options={
                'unique_together': {('grupo', 'equipo')},
            },
        ),
    ]
