# Generated by Django 5.2.7 on 2025-11-07 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneo', '0005_alter_equipo_capitan'),
        ('fase_de_grupos', '0002_equipogrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipogrupo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacion_grupo', to='Torneo.equipo'),
        ),
    ]
