# Generated by Django 5.2.7 on 2025-11-07 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fase_de_grupos', '0003_alter_equipogrupo_equipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipogrupo',
            options={'ordering': ['grupo']},
        ),
    ]
