# Generated by Django 5.2.7 on 2025-11-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fase_de_grupos', '0004_alter_equipogrupo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipogrupo',
            options={'ordering': ['-puntos']},
        ),
    ]
