# Generated by Django 5.2.7 on 2026-02-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fase_de_grupos', '0005_alter_equipogrupo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='equipos',
        ),
    ]
