# Generated by Django 5.2.7 on 2025-11-05 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneo', '0001_initial'),
        ('usuarios', '0002_alter_usuario_celular_alter_usuario_num_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='equipos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='Torneo.equipo'),
        ),
    ]
