# Generated by Django 5.2.7 on 2025-11-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='posicion',
            field=models.CharField(blank=True, choices=[('arquero', 'ARQUERO'), ('cierre', 'CIERRE'), ('ala', 'ALA'), ('pívot', 'PIVOT')], max_length=50, null=True),
        ),
    ]
