# Generated by Django 5.2.7 on 2025-11-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_posicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero_camisa',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
