# Generated by Django 5.2.7 on 2026-01-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_numero_camisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto_perfil'),
        ),
    ]
