# Generated by Django 5.2.7 on 2026-02-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero_camisa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
