# Generated by Django 5.2.7 on 2026-01-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionsolicitud',
            name='informacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
