# Generated by Django 5.2.7 on 2025-11-06 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Torneo', '0004_alter_torneo_max_equipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('pago_comprobante', models.ImageField(upload_to='comprobantes_pago/')),
                ('documento_identidad', models.FileField(upload_to='documentos_inscripcion/')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_torneo', to='Torneo.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Torneo.torneo')),
            ],
            options={
                'verbose_name': 'Inscripción a Torneo',
                'verbose_name_plural': 'Inscripciones a Torneos',
                'ordering': ['fecha_inscripcion'],
                'unique_together': {('torneo', 'equipo')},
            },
        ),
    ]
