# Generated by Django 5.2.7 on 2025-11-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escudo', models.ImageField(upload_to='escudo_equipo')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('municipio', models.CharField(help_text='Municipio del equipo', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
