# Generated by Django 5.2.7 on 2025-11-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneo', '0002_equipo_capitan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_torneo', models.ImageField(upload_to='LogoTorneo/')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('representante', models.CharField(max_length=100)),
                ('celular_contacto', models.CharField(max_length=10)),
                ('email_contacto', models.EmailField(blank=True, default='agudelochacon@gmail.com', max_length=254)),
                ('formato', models.CharField(choices=[('liga', 'Liga Todos contra Todos'), ('eliminacion', 'Eliminación Directa'), ('grupos', 'Fase de Grupos + Eliminación')], default='grupos', max_length=50)),
                ('estado', models.CharField(choices=[('inscripcion', 'En Inscripción'), ('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='inscripcion', max_length=50)),
                ('max_equipos', models.PositiveIntegerField(default=30)),
                ('fecha_inicio_inscripcion', models.DateField()),
                ('fecha_fin_inscripcion', models.DateField()),
                ('fecha_inicio_torneo', models.DateField(blank=True, null=True)),
                ('fecha_fin_torneo', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('jugadores_por_equipo', models.PositiveSmallIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': 'Torneos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
