# Generated by Django 5.2.7 on 2025-11-06 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Torneo', '0003_torneo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='max_equipos',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
