# Generated by Django 5.2.7 on 2026-01-24 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Torneo', '0005_alter_equipo_capitan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('ala_der', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular_aladerecha', to=settings.AUTH_USER_MODEL)),
                ('ala_izq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular_alaizquierda', to=settings.AUTH_USER_MODEL)),
                ('cierre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular_cierre', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='titular_equipo', to='Torneo.equipo')),
                ('pivot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular_pivot', to=settings.AUTH_USER_MODEL)),
                ('portero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titular_arquero', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
